### PR TITLE
Add shell prolog flag

### PR DESCRIPTION
**Pull request by erlanger**
Add prolog flag to point to the current shell.
As discussed in #366

### CODE REVIEW

**Comment by JanWielemaker** [comment]
I am a little worried about this after seeing the Windows hack.   I have my doubt about the hard coded path to `cmd.exe`.  One option might be to get that through `%comspec%` and the other might be not to set this variable for Windows at all because you cannot pass it the same things anyway.   In that case we should rename the variable to `unix_shell` or possibly better `posix_shell`.   What do you think?

I'm also a bit curious about the interaction with the environment variable in shell/0.  Wouldn't it be better to initialise the flag from the `SHELL` variable if this is set and only set it to UNIX_SHELL if the environment
variable does not exists?

**Comment by erlanger** [comment]
> not to set this variable for Windows at all because you cannot pass it the same things anyway.

I think this is the best thing to do; I was not going to the windows setting at all, but I thought we would discuss it.

>  Wouldn't it be better to initialise the flag from the SHELL variable if this is set and only set it to UNIX_SHELL if the environmentvariable does not exists?

Yes, I think this is much better. For some reason I thought that it would be more flexible to use SHELL at runtime, but this doesn't make sense.
Patch coming

**Comment by JanWielemaker** [comment]
Thanks.  Pushed two patches that make System() and process_create/3 always use execve()

**Comment by erlanger** [comment]
> Thanks. Pushed two patches that make System() and process_create/3 always use execve()

That's good, but why eliminate the `env(...)` option? Perhaps it was an oversight.

**Comment by JanWielemaker** [comment]
Thanks.  Merged after edit: use for System(), document and some minor issues.

**Comment by erlanger** [comment]
Great! Thanks!

**Comment by JanWielemaker** [comment]
Hmmm ...  We had a user with `SHELL=/bin/tcsh` and that now breaks saved states :worried: 

What to do?   Only using this variable if the basename is `sh` or `bash` seems hacky, but what else?

**Comment by erlanger** [comment]
> Hmmm ... We had a user with `SHELL=/bin/tcsh` and that now breaks saved states worried
> 
> What to do? Only using this variable if the basename is `sh` or `bash` seems hacky, but what else?

Yeah, I think that is too hacky. I think we could do this:

1. Leave the `posix_shell` prolog flag as it is, so that all shell related commands work properly.
2. Do not use the `posix_shell` prolog flag for `library(qsave)`, instead use the `UNIX_SHELL #cmakedefine` which comes from the `-DUNIX_SHELL` cmake variable at compile time. In this way `qsave` will not    depend on the `SHELL` environment variable or on the current `posix_shell` flag, which seems good to me.

This seems reasonable, because the requirement comes from saved states needing a sh-compatible variable which is set at compile time.

What do you think?

**Comment by JanWielemaker** [comment]
Yeah.  I see that `system()` is hard-wired to use `/bin/sh` according to the Linux docs.  `posix_shell`
however suggests we have a POSIX compliant shell and `tcsh` is not.  So, I think the way out is to 

  1. Rename the current `posix_shell` flag to `shell`
  2. Have a new `posix_shell` that is instantiated from UNIX_SHELL (better renamed into
      POSIX_SHELL) and use that for saved states and possibly a few other places.

Will you make a patch today or shall I do such?  I'll try to release 7.7.24 in the afternoon.

**Comment by erlanger** [comment]
> 
> Will you make a patch today or shall I do such? I'll try to release 7.7.24 in the afternoon.

Could you do it?  That will help me out.

**Comment by JanWielemaker** [comment]
Ok.

**Comment by erlanger** [comment]
> Yeah. I see that `system()` is hard-wired to use `/bin/sh` according to the Linux docs. `posix_shell`
> however suggests we have a POSIX compliant shell and `tcsh` is not. So, I think the way out is to
> 
>     1. Rename the current `posix_shell` flag to `shell`
> 
>     2. Have a new `posix_shell` that is instantiated from UNIX_SHELL (better renamed into
>        POSIX_SHELL) and use that for saved states and possibly a few other places.
> 
> 

Perhaps `shell` is not needed at all, which predicate will use it? `shell/1` works like `system` in linux, so it should probably use `posix_shell`.  Am I missing something?

**Comment by JanWielemaker** [comment]
> Perhaps `shell` is not needed at all

I'm a little in doubt about that, indeed.  In theory `shell/0` should use it, but that is one of the few exceptions I can think of.

**Comment by erlanger** [comment]
> > Perhaps `shell` is not needed at all
> 
> I'm a little in doubt about that, indeed. In theory `shell/0` should use it, but that is one of the few exceptions I can think of.

Yes, `shell/0` should probably use it; I was thinking of that also but I thought it was not worth the trouble since having a posix shell when you run `shell/0` is not that bad given the fact that it will be used interactively and you could just run whatever shell you wanted within the posix shell.

**Comment by JanWielemaker** [comment]
... Being the Prolog flag `posix_shell`.  Yes.  That is ok.  So I instantiate `posix_shell` from CMake
`POSIX_SHELL` (renamed from `UNIX_SHELL`) and change shell/0 as above and that is it, no?

**Comment by erlanger** [comment]
> ... Being the Prolog flag `posix_shell`. Yes. That is ok. So I instantiate `posix_shell` from CMake
> `POSIX_SHELL` (renamed from `UNIX_SHELL`) and change shell/0 as above and that is it, no?

Yup,  I think this works.

**Comment by erlanger** [comment]
> > ... Being the Prolog flag `posix_shell`. Yes. That is ok. So I instantiate `posix_shell` from CMake
> > `POSIX_SHELL` (renamed from `UNIX_SHELL`) and change shell/0 as above and that is it, no?
> 
> Yup, I think this works.

But the order for `shell/0` should be: (1) Try environment, (2) `posix_shell` prolog flag and (3) `POSIX_SHELL #define`

The order for `shell/1`  and `library(qsave)` should be: (1) `posix_shell` prolog flag, (2) `POSIX_SHELL #define`

**Pull request closed without merging**
