### PR TITLE
Create test_IEEE754.pl

### PR DESCRIPTION
**Pull request by ridgeworks**
Initial version of unit tests for IEEE 754 support. Basic coverage:
- float_XXX flags, getting and setting, functionality
- all arithmetic functions with float arguments set to IEEE special continuation values (includes new `nexttoward/2`).

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Closed means you do not want me to merge?

**Comment by ridgeworks** [comment]
Ah, yes. Should I not have done that?

**Comment by ridgeworks** [comment]
Sorry,

**Comment by ridgeworks** [comment]
Sorry, still a bit new at updating other people's code (and reading their comments, apparently).

Please merge.

**Comment by JanWielemaker** [comment]
Oops, merged using the gmp-rounding PR, which contains most of what is here.    Merged
"Late bugfix to ieee_rmode", which seems to be the only thing I missed (after duplicating some work).

I close this PR.  Please verify I got everything and then discard your own changes using `git fetch` and `git reset --hard origin/master`, so subsequent PRs are in sync again.   Thanks again for the tests.

**Pull request closed without merging**
