### PR TITLE
Add indent_string and test cases for indent_string, dedent_string derived from Python

### PR DESCRIPTION
**Pull request by kamahen**
This is a "work-in-progress", but I'm pushing it now for initial review. There's also discussion at the Discourse forum.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.  Is that the same as the diff you sent me?

**Comment by kamahen** [comment]
This is almost the same as the diff I sent. I changed the name of `string_split_lines` to `split_lines`, fixed some typos in the comments, slightly changed the @tbd comments, uncommented a few test cases, added a to-do test case (indent_empty_lines).

**Comment by kamahen** [comment]
If we decide to ignore Line Separator (\u2028) and Paragraph Separator (\u2029) -- which seems reasonable -- I'll remove splilt_lines_with_ends/4 and the tests cases for \r\n. After @JanWielemaker does a code review, I'll do a 2nd PR that changes the semantics of split_lines/2 to conform with Python (handling of trailing newline) and make it reversible; and I'll modify indent_string/3, indent_string/4, dedent_string/3 to handle whitespace-only lines the Python way (assuming everyone agrees with that design decision).

Also, I don't like the names indent_string and dedent_string ... how about indent_lines and dedent_lines? Or maybe indent_text, dedent_text? Or indent_string_lines, dedent_string_lines?

**Comment by JanWielemaker** [comment]
> dedent_string/3

Already should ignore white-space-only lines.

> Also, I don't like the names indent_string and dedent_string

I tend to agree with that.   I'm in favor indent_lines/2 and dedent_lines/2 (although, doesn't emacs call this _undent_?)

**Comment by kamahen** [comment]
Emacs uses dedent -- when I did apropos "undent" I got nothing and "dedent" got 

python-indent-dedent-line     M-x ... RET
   De-indent current line.
python-indent-dedent-line-backspace M-x ... RET
   De-indent current line.

("dedent" got many results, of course.)

**Comment by kamahen** [comment]
I'll fix bugs as I find them in the test cases rather than separate PRs (e.g., dedent_lines("", _, []) gets an uninstantiated error)

**Comment by kamahen** [comment]
I've messed up my git repository when I merged the latest update from github; rather than figure it out, I'll just close this PR and submit a new one.

**Comment by JanWielemaker** [comment]
I think we agree what it should do.   I'll wait for your new PR.

**Pull request closed without merging**
