### PR TITLE
High order tests

### PR DESCRIPTION
**Pull request by borisvassilev**
These are some _preliminary_ tests for library(dcg/high_order). I tried to test the most obvious behaviors.

There are a few things that were problematic for me.

First, I might be completely misunderstanding the idea of "nondet elements".

The test "sequence//2 order of solutions" is exactly as documented, but I am not completely clear about how this is useful.

The test "sequence//3 det element trailing sep" is the troublesome one.

The test "sequence//3 nondet element", well, I don't know what should happen. The current behavior is that it is nondet only for the last element, after the last separator. This is kinda documented but maybe a bit surprising?

Finally, should it be explicitly documented that sequence//5 cuts any choice points left by the element?

### CODE REVIEW

**Comment by JanWielemaker** [comment]
> First, I might be completely misunderstanding the idea of "nondet elements".

It means that the element is committed by the following separator or the terminating sequence (if  provided).  That allows for example for ``string(X)`` as element, where  `string//1` is from the dcg basics library and matches `.*` in a non-greedy way.

**Comment by borisvassilev** [comment]
> > First, I might be completely misunderstanding the idea of "nondet elements".
> 
> It means that the element is committed by the following separator or the terminating sequence (if provided). That allows for example for `string(X)` as element, where `string//1` is from the dcg basics library and matches `.*` in a non-greedy way.

OK, this clears up some of my confusion. So basically all the "b" element tests are bogus at the moment?

**Comment by JanWielemaker** [comment]
``sequence//3 det element trailing sep`` is hard to implement when combined with the idea that a separator commits the separator and preceding element.   The only way would be to match the separator twice, i.e., doing something like

    Element, \+ \+ Sep, !, (Sep -> [] ; [])

I'm not sure whether or not we should want that.    What is the use case?

``sequence//3 nondet element`` should produce either [b1,b1] or [b1,b2], no?

**Comment by JanWielemaker** [comment]
> So basically all the "b" element tests are bogus at the moment?

It doesn't really cover the intend.  In that sense is might be better to use string//1 or something similar that matches a variable length string in a non-greedy way.

**Comment by borisvassilev** [comment]
> `sequence//3 nondet element` should produce either [b1,b1] or [b1,b2], no?

This is indeed what it does at the moment. But this test case does not seem relevant. I'd have to clean up the tests. Using string//1 instead of my made up `b//1`.

**Comment by borisvassilev** [comment]
> `sequence//3 det element trailing sep` is hard to implement when combined with the idea that a separator commits the separator and preceding element. The only way would be to match the separator twice, i.e., doing something like
> 
> ```
> Element, \+ \+ Sep, !, (Sep -> [] ; [])
> ```
> 
> I'm not sure whether or not we should want that. What is the use case?

I don't have an obvious use case :-) so I can change this from "fixme" to "fail"?

**Comment by JanWielemaker** [comment]
> so I can change this from "fixme" to "fail"?

That is my proposal for now.   Al least this makes this case clear.

**Comment by borisvassilev** [comment]
> > so I can change this from "fixme" to "fail"?
> 
> That is my proposal for now. Al least this makes this case clear.

OK, I pushed a commit and now all tests succeed. Please feel free to fix anything else you think needs fixing, including commit messages.

**Comment by JanWielemaker** [comment]
Thanks.  Merged after adding a header and squashing the commits.   This at least makes it clearer what it should do and helps dealing with proposals to change the behavior.

**Pull request closed without merging**
