### PR TITLE
Improve CMAKE: documentation and checking of conflicting variables

### PR DESCRIPTION
**Pull request by ssardina**
Very small improvements, fixed typo and explained how to update a specific module (instead of all)

### CODE REVIEW

**Comment by ssardina** [comment]
As I install SWI with CMAKE from scratch, I am proposing some improvements to the documentation, in particular for those that are new or not so expert with CMAKE and SWI components.

**Comment by JanWielemaker** [comment]
Thanks.  I'll wait with the merge until this is settled.

**Comment by ssardina** [comment]
Excellent, I am almost finished with a full install and use of SWI+JPL to test the issue #436 that is meant to have been solved by you already. 

Will let you know when all is done so I can close issues and do the PR. Thanks.

**Comment by ssardina** [comment]
OK this is done. It should resolve issue #435 and improved the CMAKE documentation.

@JanWielemaker , I have nothing more to do here.

**Comment by JanWielemaker** [comment]
Thanks!  Squashed the changes to a single one and did a few small edits to cmake.md.

**Pull request closed without merging**
