### PR TITLE
sequence//3: commit before separator

### PR DESCRIPTION
**Pull request by pkoch**
From https://swi-prolog.discourse.group/t/confusing-behavior-of-sequence-3-and-sequence-5-from-dcg-high-order/1607

Saw `ctest` pass.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/confusing-behavior-of-sequence-3-and-sequence-5-from-dcg-high-order/1607/18

**Comment by JanWielemaker** [comment]
I'm not really sure this is going where it should.   This is in part because the main reason why I wanted the high order DCG lib was for serialization.   Even when used for matching though, there are enough cases where the separator is the right place to commit on elements.   Think of the simple case breaking a line on commas:

    sequence(string, ",", List).

A sequence of elements _separated_ by something is different from a sequence of elements _terminated_ by something.   Maybe we need two predicates?  A good alternative, but I fear not so easy to implement, is sequence//3 leaving the final separator on the input if it is not followed by an element.   Might be doable using prolog_cut_to/1 to delay committing.   Would make a bit ugly code, but if it creates an efficient and clearly defined predicate I can live with that.

**Comment by pkoch** [comment]
Could you help me out by writing the test case for that?

**Comment by pkoch** [comment]
This feels stale. Closing until someone shows enthusiasm again to move this forward!

**Pull request closed without merging**
