### PR TITLE
mode directed tabling

### PR DESCRIPTION
**Pull request by friguzzi**
Hi Jan,
this an the implementation of mode directed tabling/answer subsumption.
You can now have tabling directives of the form

```prolog
:- table pred(_,_,join).
```

that indicate that the mode for the third argument is join and the first two arguments do not have modes. join must be a ternary predicate in the same module that, given two computed answers for the third arguments, computes their combination and updates the table accordingly.
I am also attaching three test cases.

Fabrizio

path.pl:
```prolog
:- use_module(library(tabling)).
:- table connection(_,_,min).

connection(X, Y,1) :-
        connection(X, Y).
connection(X, Y,N) :-
        connection(X, Z,N1),
        connection(Z, Y),
        N is N1+1.

connection('Amsterdam', 'Schiphol').
connection('Amsterdam', 'Haarlem').
connection('Schiphol', 'Leiden').
connection('Haarlem', 'Leiden').
connection('Amsterdam', 'Leiden').

min(A,B,C):-
  (A<B->
    C=A
  ;
    C=B
  ).

/** <examples>
?- connection('Amsterdam','Leiden',N).
% N=1
*/
`
eruption.pl
`:- use_module(library(tabling)).
:- table eruption(prob_sum),sudden_energy_release/0,fault_rupture(_,prob_sum).

eruption(P)  :-
  sudden_energy_release,
  fault_rupture(_,P0),
  P is P0*0.6.
% If there is a sudden energy release under the island and there is a fault
% rupture, then there can be an eruption of the volcano on the island with
% probability 0.6

sudden_energy_release.
% The energy release occurs with certainty

fault_rupture(southwest_northeast,0.7).
fault_rupture(east_west,0.6).
% we are sure that ruptures occur

prob_sum(A,B,C):-
  C is 1-(1-A)*(1-B).


/** <examples>
?- eruption(P).
%P = 0.6288.
*/
```

sneezing.pl:
```prolog
:- use_module(library(tabling)).
:- table sneezing(_,prob_sum),flu(_,prob_sum),hay_fever(_,prob_sum).

sneezing(X,P) :- flu(X,P0), P is P0*0.3.
% if X has the flu, there is a probability of 0.3 that he sneezes

sneezing(X,P) :- hay_fever(X,P0), P is P0*0.2.
% if X has hay fever, there is a probability of 0.2 that he sneezes

flu(bob,0.2).
% bob has the flu with prob 0.2

hay_fever(bob,0.4).
% bob has hay fever with prob 0.4





prob_sum(A,B,C):-
  C is 1-(1-A)*(1-B).

/** <examples>
?- sneezing(bob,P).
%P = 0.1352000000000001.
*/`
```

### CODE REVIEW

**Comment by friguzzi** [comment]
here are the files on gist

[test cases](https://gist.github.com/friguzzi/740adaf83b31c01965982a44d0f74f49)

**Comment by friguzzi** [comment]
"added implementation for YAP_MkNewApplTerm(functor_t f, int arity)"
is an old commit that I forgot to pull request you, it adds stuff function to the yap interface

**Comment by JanWielemaker** [comment]
Whow!  I'm going to have a deep look into this :)

**Comment by JanWielemaker** [comment]
This one is merged long ago

**Pull request closed without merging**
