### PR TITLE
ENHANCED: allow installation of tests with -DINSTALL_TESTS

### PR DESCRIPTION
**Pull request by erlanger**
First try to install tests (to be executed in the target device) and enhance `test.pl` to test packages.
Discussed in #358.

### CODE REVIEW

**Comment by erlanger** [comment]
I missed the fact that some packages don't have a test_<pkgname>.pl script including all the other tests.

Should I rework the test.pl script to run any test_*.pl file within the package directory? Or is it better to require a package to have a test_<pkgname>.pl script?

**Comment by erlanger** [comment]
Some tests actually call `halt` (e.g. inclpr)or in the case of JPL on android are aborting (probably `SIGABRT`).

 This means the `test.pl` framework used for packages can't use `load_files`, I am thinking of simply starting an new `swipl` process for each package. Do you think this is the right approach?

**Comment by JanWielemaker** [comment]
I scanned though the patch.  As we have some open issues I won't merge right now.  Remarks:

  - I'd be in favour of just copying the test_*.pl files from the packages.  That should work for all
    but a few that require additional data.  For those we can add a conditional bit to the package
    CMakeLists.txt to copy the test data.
 - test_* scripts that call halt should be rewritten.  
 - test scripts that may abort should be rewritten.  I think that is realistically only the java test.
   The script may simply execute Prolog itself using process_create/3 using the executable
   as available through the Prolog flag.   I guess the main driver can set some flag so we know
   this is needed.
 - I don't think we need a test_<package>.pl  Not sure here.  I think there should be none/very few
   exceptions and if these exist we can probably rename the file or add a block-list to test.pl

Does this make sense?

**Comment by erlanger** [comment]
> Does this make sense?

Sure, good guidance!
I'll get to work on it.

> test scripts that may abort should be rewritten. I think that is realistically only the java test.
The script may simply execute Prolog itself using process_create/3 using the executable
as available through the Prolog flag.

The only problem here is that running on Android requires the environment variable `LD_PRELOAD=libswipl.so:libm.so` (and for JPL) `libnative.so` before running the executable. `process_create/3` is not passing the environment variables (which is the reason why the 3 `saved_state` tests fail, since they use `process_create` to run the newly minted executable.

This happens because the Android dynamic linker (the equivalent of `ld.so`) is broken, and makes symbols globally visible only for libraries in LD_PRELOAD (or for symbols on the main file).

I'll experiment linking each package `.so` with `libswipl.so` and `libm.so` and to set some variable in the package CMakeLists.txt to point to extra libraries that may be needed (like `libnativehelper.so` for JPL on Android). I think I'll try to solve this first, and then continue the work on `INSTALL_TESTS`.
Does this seem reasonable?

**Comment by JanWielemaker** [comment]
> `process_create/3` is not passing the environment variables

If that is true, it is broken.   In Linux (Fedora 28 today), I get a nice environment using

    ?- process_create(path(printenv), [], []).

**Comment by erlanger** [comment]
> If that is true, it is broken. In Linux (Fedora 28 today), I get a nice environment using
> ?- process_create(path(printenv), [], []).

hmm, you are right,  I presumed there was a problem with that due the [documentation](http://www.swi-prolog.org/pldoc/doc_for?object=process_create/3) in  which says:
 "Note that the current implementation does not pass any environment variable"

I just tested, and `process_create` is properly passing the environment variables. But there is some other problem with it:
```
$ pwd
/data/data/com.termux/files/usr/lib/swipl/test/Tests/save
$ swipl -o p -g echo_true -c input/plain.pl
$ ls -al p
-rwx------    1 u0_a241  u0_a241     667471 Nov 22 07:53 p
$ swipl
Welcome to SWI-Prolog (threaded, 32 bits, version 7.7.22-28-g3d27e9a6a-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- process_create('./p',[],[]).
/data/data/com.termux/files/usr/lib/swipl/test/Tests/save/p: No such file or directory
ERROR: Process "/data/data/com.termux/files/usr/lib/swipl/test/Tests/save/p": exit status: 1
ERROR: In:
ERROR:    [9] process:process_create('/data/data/com.termux/files/usr/lib/swipl/test/Tests/save/p',[])
ERROR:    [7] <user>
ERROR:
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
?-
% halt
$ ./p
true.
$
```

But this works:
```
?- process_create(path(ls),['-al','./p'],[]).
-rwx------    1 u0_a241  u0_a241     667471 Nov 22 07:53 ./p
true.
```

and this:
```
$ MYVAR=hello swipl
Welcome to SWI-Prolog (threaded, 32 bits, version 7.7.22-28-g3d27e9a6a-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- process_create(path(env),[],[]).
USER=u0_a241
SSH_CLIENT=<deleted>
EXTERNAL_STORAGE=/storage/emulated/legacy
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
SHLVL=1
OLDPWD=/data/data/com.termux/files/usr/lib/swipl/test/Tests
HOME=/data/data/com.termux/files/home
SSH_TTY=/dev/pts/1
TMPDIR=/data/data/com.termux/files/usr/tmp
LOGNAME=u0_a241
_=/data/data/com.termux/files/usr/bin/swipl
TERM=xterm-256color
ANDROID_DATA=/data
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
ANDROID_ROOT=/system
LANG=en_US.UTF-8
LD_PRELOAD=libswipl.so:libm.so
TMP=/data/data/com.termux/files/home/tmp
PREFIX=/data/data/com.termux/files/usr
SHELL=/data/data/com.termux/files/usr/bin/sh
MYVAR=hello
PWD=/data/data/com.termux/files/usr/lib/swipl/test/Tests/save
SSH_CONNECTION=<deleted>
LINES=31
COLUMNS=195
true.
```

**Comment by JanWielemaker** [comment]
> Does this make sense to you?

Not for `process_create/3` as this comes from `packages/clib/process.c`.  Otherwise it makes sense to replace all hard-coded "/bin/sh" with the UNIX_SHELL.  Note that this particular one is written by library(qsave) from Prolog.  I guess we need a Prolog flag `shell` that is initialized from UNIX_SHELL in
`os/pl-prologflag.c`.  Ideally we also use this shell from shell/0 and shell/1, such that the user can set the
shell from Prolog.

**Comment by JanWielemaker** [comment]
Will you add the flag `shell` or shall I do so?

**Comment by erlanger** [comment]
> Not for process_create/3 as this comes from `packages/clib/process.c`.

Ahh, you're right about the different file, but we have the same problem in [`packages/clib/process.c`](https://github.com/SWI-Prolog/packages-clib/blob/master/process.c#L1658):
```c
   if ( info->envp )
      execve(info->exe, info->argv, info->envp);
    else
      execv(info->exe, info->argv);
```
So if we call without an environment then `execv` is called (and not `execve`).


> Otherwise it makes sense to replace all hard-coded "/bin/sh" with the UNIX_SHELL. Note that this particular one is written by library(qsave) from Prolog. I guess we need a Prolog flag shell that is initialized from UNIX_SHELL in os/pl-prologflag.c. Ideally we also use this shell from shell/0 and shell/1, such that the user can set the shell from Prolog.

Great idea! I'll work on it.

**Comment by erlanger** [comment]
> Will you add the flag shell or shall I do so?

I'll work on it

**Comment by JanWielemaker** [comment]
> info->envp

Note that process_create/3 uses posix_spawn() when available and fork/exec only if a directory is specified as posix_spawn strangely cannot change directory for the child.

The environment handling requires some cleanup and a way to extend the environment, leaving existing variables alone.    I'll have a look.

**Comment by erlanger** [comment]
For Android:
```
-- Looking for posix_spawn
-- Looking for posix_spawn - not found
```

**Comment by erlanger** [comment]
> Ok. Of course we can simply change the execv to execve and pass environ. I guess we can so so unconditionally?

Yes, I think this is the best. It will allow running things normally under termux.

BTW, I also sent the PR with qsave using the shell prolog flag. I think we should also use the shell prolog flag for as much as we can, because we should not depend on `termux-exec` to shuffle shebangs around.

**Comment by erlanger** [comment]
New implementation of -DINSTALL_TESTS
-----------------------------------------------------------
Okay, I think I have a much cleaner way to run the tests at run time (issue #366). Included are the patches that do the following:
* During build time write a `cmake_pkg_tests.db`
* `cmake_pkg_tests.db` is a list of facts indicating the different tests that `ctest` runs. It has enough information to run each test within `test.pl`.
* `test.pl` is modified to be able to run these tests with the `--packages` or `--package=XXX` command line options.
* Updated some packages so that they load modules using `file_search_path` so that we avoid conflicts with duplicate files, prevent duplicate copies, and allow the developers to test with local modules in the source directory.

Don't know what the conflict with `packages/ssl` is, I probably just missed a previous commit you made.

**Comment by erlanger** [comment]
I would like to run `test.pl` from within swipl, having a predicate similar to `check_installation`. Something like `test_installation`. It will just run all the tests if the build was compiled with `-DINSTALL_TESTS` otherwise it prints an informational message saying the no tests are available because the build was done without `-DINSTALL_TESTS`. What do you think?

**Comment by JanWielemaker** [comment]
Looks good (not tested though).   I would like to see the installation of specific files for packages such as Yaml, protobufs, etc., to be moved into the packages themselves.  This improves modularity and ensures we install only tests for packages that are actually installed.   The general copy of test files for a package can probably go to add_test(), so again we only install for packages that are really active.

Agree?

Getting really close!   Being able to install the tests is a nice addition.  They are not that big and doing so might be worthwhile in many cases were the build environment differs from the deployment environment.

**Comment by JanWielemaker** [comment]
> I would like to run `test.pl` from within swipl, having a predicate similar to `check_installation`. Something like `test_installation`. It will just run all the tests if the build was compiled with `-DINSTALL_TESTS` otherwise it prints an informational message saying the no tests are available because the build was done without `-DINSTALL_TESTS`. What do you think?

I'm in favor.  I think that can be added to `check_installation.pl`.  It is related closely enough.

**Comment by erlanger** [comment]
> Looks good (not tested though). I would like to see the installation of specific files for packages such as Yaml, protobufs, etc., to be moved into the packages themselves. This improves modularity and ensures we install only tests for packages that are actually installed. The general copy of test files for a package can probably go to add_test(), so again we only install for packages that are really active.
> 
> Agree?

Great, yes, this makes total sense, I should have thought about it.

**Comment by erlanger** [comment]
> I'm in favor. I think that can be added to `check_installation.pl`. It is related closely enough.
Good, I'll work on it.

**Comment by erlanger** [comment]
Workng
----------
Phew! That was quite a bit of work, but it is done!
The following is working:
* `ctest -j 8` from the build directory
*  `<install_dir>/bin/swipl -f none test.pl` from the `<PREFIX>/lib/swipl/test` directory
*  `<install_dir>/bin/swipl -f none test.pl --packages` from the `<PREFIX>/lib/swipl/test` directory
*  `<install_dir>/bin/swipl -f none test.pl --package=<pkg>` from the `<PREFIX>/lib/swipl/test` directory

Help needed
-----------------
* Running `test_installation` from the top level gives this error (all the other tests work):
```
(test_call.pl)...................
ERROR: /tmp/s1/lib/swipl/test/Tests/core/test_call.pl:159:
        test c_cm1 is subject to occurs check (STO):
ERROR: Finite trees (error checking): received error: plunit_cross_module_call:c_cm1/1: Undefined procedure: foo:cm1/1
ERROR: Rational trees: received error: plunit_cross_module_call:c_cm1/1: Undefined procedure: foo:cm1/1
ERROR: Finite trees: received error: plunit_cross_module_call:c_cm1/1: Undefined procedure: foo:cm1/1
ERROR: /tmp/s1/lib/swipl/test/Tests/core/test_call.pl:162:
        test c_cm2 is subject to occurs check (STO):
ERROR: Finite trees (error checking): received error: plunit_cross_module_call:c_cm2/1: Undefined procedure: foo:cm2/1
ERROR: Rational trees: received error: plunit_cross_module_call:c_cm2/1: Undefined procedure: foo:cm2/1
ERROR: Finite trees: received error: plunit_cross_module_call:c_cm2/1: Undefined procedure: foo:cm2/1
```

I can't figure out how this error is happening, because I have the plunit `STO` flag set to `false` for the core/main tests (proved by the fact that it runs OK from the command-line, but not from the top-level).
Could you take a look to see what the problem is?

**Comment by JanWielemaker** [comment]
> Workng

Thanks a lot.  I'll do the next round reviewing and see whether I can find more about the above issue.  It will probably take a few days though if I look at my agenda for today and tomorrow.

**Comment by JanWielemaker** [comment]
I had to rush after pushing the merges.   You found them anyway :)   Your patches worked as is.  Some of the modifications to the packages were not needed.  I guess the result of older attempts.

> So probably the best thing to do is to add a COMMAND argument to the `test_lib` function so that it can be recorded in the `cmake_pkg_tests.db` file. What do you think?

Makes sense to me.

I do see there is far too much data in the `test` dir, including even the `.git`.  I'll have a look at that.  If we can get it small we could for example include it with the Windows distribution as the binary runs a wide variety of Windows versions, but possibly not always as it should ...

**Comment by JanWielemaker** [comment]
Pushed a series of commits that restrict installation of test files for just the needed files.    Please use this as the basis for further patches.   You might consider just adding a `if(INSTALL_TESTS)` section to the JPL CMakeLists.txt file.  That might be easier to understand than more logic to test_libs().  I decided for this route for some packages that needed files and directories from weird places.

It is still a little big to add to e.g. the Windows installers (6.5 Mb), but we could add a .zip (960Kb).

**Comment by erlanger** [comment]
>  You might consider just adding a `if(INSTALL_TESTS)` section to the JPL CMakeLists.txt file.

This won't work for the JPL test that I was mentioning, because the test consists in running a Java VM connecting to swipl, it is not the case of a missing file. 

In any case, this is useless for Android, because  a java VM is not started from the command line.  The only reason why I was concerned about it is for 100% consistency between `test_installation` and  `ctest`. In this case it is 99.99% consistent, only missing that `prolog_in_java` test.


> 
> It is still a little big to add to e.g. the Windows installers (6.5 Mb), but we could add a .zip (960Kb).

Would not the windows installer zip the contents automatically?

**Comment by JanWielemaker** [comment]
> In this case it is 99.99% consistent, only missing that `prolog_in_java` test.

That is fine with me, surely for now.   As a related question: is this Termux version just that or is it a promising step to create Android apps that contain Prolog?  I'd assume this requires us to be able to embed Prolog in Java, no?

> Would not the windows installer zip the contents automatically?

Yes.  Adding 10% to both the installer and the installed system seems a bit of an overkill for this though.   I'm keen to avoid SWI-Prolog becoming _bloatware_ ...

As far as I'm concerned we can close this issue.  Please do if you agree.

**Comment by erlanger** [comment]
>  As a related question: is this Termux version just that or is it a promising step to create Android apps that contain Prolog? I'd assume this requires us to be able to embed Prolog in Java, no?
> 

Yes, it is certainly a very promising step, since termux itself is a Java Android app. 

> Yes. Adding 10% to both the installer and the installed system seems a bit of an overkill for this though. I'm keen to avoid SWI-Prolog becoming _bloatware_ ...

Yes, I agree. It will be used mostly by developers.

**Pull request closed without merging**
