### PR TITLE
Paths in .gitmodules are now absolute.

### PR DESCRIPTION
**Pull request by gl-yziquel**
https://github.com/SWI-Prolog/swipl-devel/issues/1283

### CODE REVIEW

**Comment by JanWielemaker** [comment]
IMO relative URLs are the way to go for a single project split into multiple modules.    Only when using truly external repos as submodules is a good reason to use absolute URLs.    For one thing, it allows cloning using SSH or HTTP for the entire repository.

Unfortunately, GitHub is not very cooperative as it does not allow organizing repositories in directories.   When the project was still self-hosted we used directories and one could nicely clone clones.    I did a quick checks with github and gitlab, but I failed to get definitive answers.    The other hope would be that git cloning gets smarter ...

Alternative to your solution, you can create links from the parent of swipl-devel like

      ln -s swipl-devel/packages/clib packages-clib
      etc.

It is a bit awkward too :cry:

**Comment by gl-yziquel** [comment]
> Unfortunately, GitHub is not very cooperative as it does not allow organizing repositories in directories. When the project was still self-hosted we used directories and one could nicely clone clones. I did a quick checks with github and gitlab, but I failed to get definitive answers. The other hope would be that git cloning gets smarter ...

Well, I'd maybe suggest using the repo or jiri tool to create a manifest. This way, you can pull everything in one go, with relative paths, and have only one place in the manifest to change if one wishes to move from github, gitlab, sourcehut, or self-hosting.

Anyway. It's just a pain. I experience that git clone of clone + submodules with quite a number or repos, as a matter of fact.

**Comment by JanWielemaker** [comment]
It seems this can be solved using gitlab groups and subgroups.    All in all, I'm not convinced that a migration to gitlab is worth the trouble.     I might at a script to the `scripts` directory that can be called to prepare the repo for recursive cloning.     That seems to be as good as it gets with github.

**Comment by gl-yziquel** [comment]
Your call. I take things as they are.

**Pull request closed without merging**
