### PR TITLE
ENHANCED: added cputime_resolution to is/2

### PR DESCRIPTION
**Pull request by kamahen**

### CODE REVIEW

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/arithmetic-function-cputime-resolution/5560/10

**Comment by JanWielemaker** [comment]
Thanks.  But ... see Discourse comments.

**Comment by eshelyaron** [comment]
A thought: with this patch, unless `defined(HAVE_CLOCK_GETTIME) && defined(CLOCK_PROCESS_CPUTIME_ID)`,

**Comment by JanWielemaker** [comment]
Thanks.  I think it is not worth it.   Rick was clearly after something else and I do not see any Prolog application to use this information.    That added to the portability and documentation including claims on portability doesn't make it worthwhile until someone comes up with a concrete need.

**Comment by kamahen** [comment]
OK ... I "solved" the portability issues by returning 0.0 if there was no support for `clock_getres()`. ;)

**Comment by JanWielemaker** [comment]
Infinity is another choice :smile:

**Comment by kamahen** [comment]
So is `nan`, although ...
```
?- X is nan.
X = 1.5NaN.
```
???

**Pull request closed without merging**
