### PR TITLE
Fix documentation of first_solution/3.

### PR DESCRIPTION
**Pull request by edechter**
Example was missing the empty third option argument.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
???  Is this still an issue?  Will you make a new pull request?

**Comment by edechter** [comment]
Yes. I did not mean to close this, and I don't know how I did.

**Comment by JanWielemaker** [comment]
Hmm.  It is conflicting and wasn't a plain pull requests anyway (lots of merges).  Please either send the diff or make a plain one relative to master.  Re-closing this one.

**Comment by edechter** [comment]
Sorry, I'm really confused about how to make a clean pull request and deal with the submodules... Here's the diff: 

```

@@ -336,7 +336,8 @@ same_length([_|T1], [_|T2], [_|T3]) :-
 %	search_graph(Grap, Path) :-
 %		 first_solution(Path, [ breadth_first(Graph, Path),
 %				        depth_first(Graph, Path)
-%				      ]).
+%				      ],
+%                              []).
 %	==
 %
 %	Options include thread stack-sizes passed   to thread_create, as

```

**Comment by edechter** [comment]
```
diff --git a/library/thread.pl b/library/thread.pl
index 702f813..c41e735 100644
--- a/library/thread.pl
+++ b/library/thread.pl
@@ -336,7 +336,8 @@ same_length([_|T1], [_|T2], [_|T3]) :-
 %	search_graph(Grap, Path) :-
 %		 first_solution(Path, [ breadth_first(Graph, Path),
 %				        depth_first(Graph, Path)
-%				      ]).
+%				      ],
+%                              []).
 %	==
 %
 %	Options include thread stack-sizes passed   to thread_create, as
-- 
```

**Pull request closed without merging**
